#!/bin/bash
# Setup Google Cloud pour SimplePlate

echo "=== Setup Google Sheets API pour SimplePlate ==="
echo ""
echo "1. Va sur https://console.cloud.google.com/"
echo "2. Connecte-toi avec: playaxel83310@gmail.com"
echo "3. Crée un nouveau projet 'SimplePlate'"
echo "4. Active l'API Google Sheets:"
echo "   - Menu hamburger → APIs & Services → Library"
echo "   - Cherche 'Google Sheets API' → Enable"
echo "5. Crée un Service Account:"
echo "   - APIs & Services → Credentials"
echo "   - Create Credentials → Service Account"
echo "   - Nom: simpleplate-agent"
echo "   - Role: Editor"
echo "6. Crée une clé JSON:"
echo "   - Clique sur le Service Account créé"
echo "   - Keys → Add Key → Create New Key → JSON"
echo "   - Télécharge le fichier (ex: simpleplate-xxx.json)"
echo "7. Envoie-moi ce fichier JSON"
echo ""
echo "Une fois que tu m'envoies le fichier, je configure tout automatiquement."
echo ""
